version: '3.2'

services:
  userswebapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLISH_PROFILE: ./Properties/PublishProfiles/CustomProfile.pubxml
        SOLUTION: UsersWebApi.sln
    entrypoint: dotnet UsersWebApi.dll
    ports:
      - 8080:80
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
        SA_PASSWORD: Your_password123
        ACCEPT_EULA: Y
        MSSQL_PID: Express
    ports:
      - 1433:1433
networks:
  internal:
